import type { EvidenceMedia } from "./types";

export const evidenceMedia: readonly EvidenceMedia[] = [
  {
    id: "bdb-task-control",
    ownerId: "bdb",
    role: "primary",
    src: "/evidence/bdb/bdb-task-control.webp",
    alt: "BDB task control center showing a bounded development workflow and reviewed task state.",
    caption: "Task Control Center / controlled workflow",
    sourceKind: "user_approved_screenshot",
    publicSafe: true,
    contentHash: "4a622248fb29c67205fef0aba916da08c35867192ea329de0f04cca887757634",
    width: 1529,
    height: 976,
  },
  {
    id: "bdb-workspace",
    ownerId: "bdb",
    role: "secondary",
    src: "/evidence/bdb/bdb-workspace.webp",
    alt: "Public-safe crop of the BDB workspace management surface for the Brenych Agent Interface project.",
    caption: "Workspace management / BAI registered project",
    sourceKind: "user_approved_screenshot",
    publicSafe: true,
    contentHash: "03f161386c25cc3a29ef504054a270e9281b9fef7e7204c8dc30481acff35f2b",
    width: 954,
    height: 870,
  },
  {
    id: "distribution-campaign-setup",
    ownerId: "distribution-desk",
    role: "primary",
    src: "/evidence/distribution-desk/distribution-campaign-setup.webp",
    alt: "Distribution Desk campaign preparation screen with structured publishing workflow controls.",
    caption: "Campaign preparation / structured workflow",
    sourceKind: "user_approved_screenshot",
    publicSafe: true,
    contentHash: "59a98a89227da4cecb17073bd084352503e529b7a8183ad66a940238f24f37ea",
    width: 1642,
    height: 1050,
  },
  {
    id: "distribution-campaign-workspace",
    ownerId: "distribution-desk",
    role: "secondary",
    src: "/evidence/distribution-desk/distribution-campaign-workspace.webp",
    alt: "Distribution Desk campaign workspace showing a durable continuation state for publication work.",
    caption: "Campaign workspace / continuation state",
    sourceKind: "user_approved_screenshot",
    publicSafe: true,
    contentHash: "ac7df387f8f6ee842ca1182b5961386a6eb8c46a3130abffe4e93c7dc1dd756c",
    width: 1601,
    height: 962,
  },
  {
    id: "storyform-editor-workflow",
    ownerId: "storyform",
    role: "primary",
    src: "/evidence/storyform/storyform-editor-workflow.webp",
    alt: "StoryForm storyboard-first narrative workspace with editorial, media, and AI workflow surfaces.",
    caption: "Storyboard + AI workflow + editing surface",
    sourceKind: "user_approved_screenshot",
    publicSafe: true,
    contentHash: "25ec7624aa32bbc65d3166198276e124d0dc243524321243e9496801c364b568",
    width: 1868,
    height: 1099,
  },
  {
    id: "model-site-portfolio",
    ownerId: "model-site",
    role: "primary",
    src: "/evidence/model-site/model-site-portfolio.webp",
    alt: "Public spatial model portfolio presenting a composed profile and authored image-led interface.",
    caption: "Public model portfolio",
    sourceKind: "user_approved_screenshot",
    publicSafe: true,
    contentHash: "70cc304ec1d2c14c688fccdffd4e53d2416049a2d28a5f4222ac5262675d10e7",
    width: 2000,
    height: 1156,
  },
  {
    id: "model-site-builder",
    ownerId: "model-site",
    role: "secondary",
    src: "/evidence/model-site/model-site-builder.webp",
    alt: "Model Site live builder showing structured assisted portfolio management beside a spatial preview.",
    caption: "Live builder / assisted portfolio management",
    sourceKind: "user_approved_screenshot",
    publicSafe: true,
    contentHash: "7c22fd64613f44c8d5d9390460a142a0d3c97e01a116adb3a1194fe577181b11",
    width: 2200,
    height: 1088,
  },
  {
    id: "photo-web-entry",
    ownerId: "photo-web",
    role: "primary",
    src: "/evidence/photo-web/photo-web-entry.webp",
    alt: "Rostyslav Brenych photography site opening with an authored art-fashion editorial composition.",
    caption: "Authored photography entry",
    sourceKind: "user_approved_screenshot",
    publicSafe: true,
    contentHash: "d13d33296b9aeee4c3941338fd4c9bb099c0b63df308ee7ea2e93e4d776482e8",
    width: 2400,
    height: 1658,
  },
  {
    id: "photo-web-series",
    ownerId: "photo-web",
    role: "secondary",
    src: "/evidence/photo-web/photo-web-series.webp",
    alt: "Photography series interface arranged as a living editorial field with cinematic navigation.",
    caption: "Living series field",
    sourceKind: "user_approved_screenshot",
    publicSafe: true,
    contentHash: "065345ed7d64da081b33b5e3b70723127934768ba62c5a930980a74d41441405",
    width: 2400,
    height: 1658,
  },
  {
    id: "artist-stage-meta-bodies",
    ownerId: "artist-stage",
    role: "primary",
    src: "/evidence/artist-stage/artist-stage-meta-bodies.webp",
    alt: "Artist Stage Meta Bodies home field with cinematic artwork, atmosphere, and editorial typography.",
    caption: "Meta Bodies authored field",
    sourceKind: "user_approved_screenshot",
    publicSafe: true,
    contentHash: "17d33c30635eea36cfdf1097ce6f1c2a9b56e21db504cc4ddaa403a775c3021e",
    width: 2560,
    height: 1698,
  },
  {
    id: "artist-stage-inner-structures",
    ownerId: "artist-stage",
    role: "secondary",
    src: "/evidence/artist-stage/artist-stage-inner-structures.webp",
    alt: "Artist Stage Inner Structures series view with a living cinematic artwork constellation.",
    caption: "Inner Structures living series field",
    sourceKind: "user_approved_screenshot",
    publicSafe: true,
    contentHash: "537d6195d3cda4ddadd46035a22e1c7aba7b4e39bd59ac32cc034ffa0211ae14",
    width: 2560,
    height: 1640,
  },
  {
    id: "webhero-living-environments",
    ownerId: "webhero",
    role: "primary",
    src: "/evidence/webhero/webhero-living-environments.webp",
    alt: "WEBHERO WebGL stage presenting interfaces as living spatial environments.",
    caption: "Interfaces as living environments",
    sourceKind: "user_approved_screenshot",
    publicSafe: true,
    contentHash: "d62eec3c9a8528a97f04c020bc06ab2ec0abf870f8eedb1e34d9440fe79b111d",
    width: 2560,
    height: 1524,
  },
  {
    id: "webhero-metamorph-bubbles",
    ownerId: "webhero",
    role: "secondary",
    src: "/evidence/webhero/webhero-metamorph-bubbles.webp",
    alt: "WEBHERO Metamorph Bubbles stage showing a sculptural WebGL object in a cinematic field.",
    caption: "Metamorph Bubbles / WebGL object proof",
    sourceKind: "user_approved_screenshot",
    publicSafe: true,
    contentHash: "7cbdd5798b72cf1119819e4c4cfe130977d60f5e3b4ba482cc2674fed30fee0d",
    width: 2560,
    height: 1524,
  },
  {
    id: "weekfield-smart-mix",
    ownerId: "weekfield",
    role: "primary",
    src: "/evidence/weekfield/weekfield-smart-mix.webp",
    alt: "Weekfield Smart Mix workspace showing a structured, human-reviewed planning proposal.",
    caption: "Smart Mix",
    sourceKind: "user_approved_screenshot",
    publicSafe: true,
    contentHash: "74d59b903a69a682e5d4020b4d5bb971ec1927b417b2042865095dd26dc636f2",
    width: 2560,
    height: 1640,
  },
  {
    id: "weekfield-planet-field",
    ownerId: "weekfield",
    role: "secondary",
    src: "/evidence/weekfield/weekfield-planet-field.webp",
    alt: "Weekfield Planet Field showing a spatial planning surface for a recoverable Week Pack workflow.",
    caption: "Planet Field",
    sourceKind: "user_approved_screenshot",
    publicSafe: true,
    contentHash: "3af743d180fad05c3c657d52daf1dd66ed6c69a696d364b46aa7312f5fb47aba",
    width: 2560,
    height: 1640,
  },
  {
    id: "presence-os-memory-field",
    ownerId: "presence-os-memory-atlas",
    role: "primary",
    src: "/evidence/presence-os-memory-atlas/presence-os-memory-field.webp",
    alt: "Presence OS Memory Atlas entry screen with a dark spatial memory field and four image cards arranged around a central signal.",
    caption: "Memory Atlas entry field",
    sourceKind: "user_approved_screenshot",
    publicSafe: true,
    contentHash: "5ba51cd14175b8386ed032075a6fb39a49b8199f39d97808b76bca751a9978bb",
    width: 3978,
    height: 2368,
  },
  {
    id: "presence-os-spatial-inspect",
    ownerId: "presence-os-memory-atlas",
    role: "secondary",
    src: "/evidence/presence-os-memory-atlas/presence-os-spatial-inspect.webp",
    alt: "Presence OS Memory Atlas demo field with a central coast image, surrounding memory cards, and a recovered-memory status panel.",
    caption: "Spatial memory field / recovered trace",
    sourceKind: "user_approved_screenshot",
    publicSafe: true,
    contentHash: "7d7d39a36a14495a92c2c728baa0774bfab9ebb9a5f227522078196f32dc2e17",
    width: 3978,
    height: 2368,
  },
  {
    id: "sprintcrm-workspace",
    ownerId: "sprintcrm",
    role: "primary",
    src: "/evidence/sprintcrm/sprintcrm-workspace.webp",
    alt: "SprintCRM opening screen with Import, Today, and Pipeline cards beside a sign-in panel with blank email and password fields.",
    caption: "SprintCRM operator workspace entry",
    sourceKind: "user_approved_screenshot",
    publicSafe: true,
    contentHash: "1f4cd230b3bee9b7169f3de2ef93eb8d8f490c79fad62c1eae2711b6d952863c",
    width: 1597,
    height: 1000,
  },
] as const;

export const mediaForOwner = (ownerId: EvidenceMedia["ownerId"]): readonly EvidenceMedia[] =>
  evidenceMedia.filter((item) => item.ownerId === ownerId);
