import type { Capability } from "./types";

export const capabilities: readonly Capability[] = [
  {
    id: "electron",
    label: "Electron",
    category: "Desktop applications",
    source: "Public evidence records",
    summary: "Desktop application delivery using Electron.",
    aliases: ["desktop app", "desktop application"],
    relatedCapabilityIds: [],
  },
  {
    id: "mcp",
    label: "MCP",
    category: "Agent interfaces",
    source: "Public evidence records",
    summary: "Model Context Protocol integration work.",
    aliases: ["model context protocol"],
    relatedCapabilityIds: ["ai-automation"],
  },
  {
    id: "ai-automation",
    label: "AI automation",
    category: "Workflow automation",
    source: "Public evidence records",
    summary: "Operator-facing AI-assisted workflow automation.",
    aliases: ["ai assisted automation"],
    relatedCapabilityIds: [],
  },
  {
    id: "supabase",
    label: "Supabase",
    category: "Product workflows",
    source: "Public evidence records",
    summary: "Supabase-backed product workflows.",
    aliases: [],
    relatedCapabilityIds: ["operator-workflow"],
  },
  {
    id: "crm",
    label: "CRM",
    category: "Product workflows",
    source: "Public evidence records",
    summary: "Customer relationship workflow interfaces.",
    aliases: ["customer relationship management"],
    relatedCapabilityIds: ["operator-workflow"],
  },
  {
    id: "gmail-communication",
    label: "Gmail communication",
    category: "Communication workflows",
    source: "Public evidence records",
    summary: "Gmail-centered communication workflows.",
    aliases: ["gmail", "email communication"],
    relatedCapabilityIds: ["crm"],
  },
  {
    id: "operator-workflow",
    label: "Operator workflow",
    category: "Product workflows",
    source: "Public evidence records",
    summary: "Operational interfaces for repeated human workflows.",
    aliases: ["operations workflow"],
    relatedCapabilityIds: [],
  },
  {
    id: "webgl-3d-web",
    label: "WebGL / 3D web",
    category: "Spatial web",
    source: "Public evidence records",
    summary: "Interactive three-dimensional web interfaces.",
    aliases: ["webgl", "3d web"],
    relatedCapabilityIds: ["interactive-interface"],
  },
  {
    id: "webxr",
    label: "WebXR",
    category: "Spatial web",
    source: "Public evidence records",
    summary: "WebXR interface exploration.",
    aliases: ["xr"],
    relatedCapabilityIds: ["webgl-3d-web"],
  },
  {
    id: "spatial-archive",
    label: "Spatial archive",
    category: "Spatial web",
    source: "Public evidence records",
    summary: "Spatially organized archive interfaces.",
    aliases: ["spatial memory"],
    relatedCapabilityIds: ["webxr"],
  },
  {
    id: "interactive-interface",
    label: "Interactive interface",
    category: "Interactive interfaces",
    source: "Public evidence records",
    summary: "Public interactive interface design and implementation.",
    aliases: ["interactive ui"],
    relatedCapabilityIds: [],
  },
  {
    id: "publishing-workflow",
    label: "Publishing workflow",
    category: "Editorial workflows",
    source: "Public evidence records",
    summary: "Desktop publishing workflow support.",
    aliases: [],
    relatedCapabilityIds: [],
  },
  {
    id: "integration-workflow",
    label: "Integration workflow",
    category: "Product workflows",
    source: "Public evidence records",
    summary: "Product integration workflow foundations.",
    aliases: [],
    relatedCapabilityIds: [],
  },
  {
    id: "media-workflow",
    label: "Media workflow",
    category: "Editorial workflows",
    source: "Public evidence records",
    summary: "Desktop editorial media tooling workflows.",
    aliases: [],
    relatedCapabilityIds: [],
  },
  {
    id: "site-control-architecture",
    label: "Site-control architecture",
    category: "Site control",
    source: "Public evidence records",
    summary: "Site-control architecture foundations.",
    aliases: [],
    relatedCapabilityIds: [],
  },
  {
    id: "control-contracts",
    label: "Control contracts",
    category: "Site control",
    source: "Public evidence records",
    summary: "Control contract foundations.",
    aliases: [],
    relatedCapabilityIds: [],
  },
  {
    id: "manifest-revision-validation",
    label: "Manifest, revision, and validation",
    category: "Site control",
    source: "Public evidence records",
    summary: "Manifest, revision, diff, validation, apply, and verification foundations.",
    aliases: [],
    relatedCapabilityIds: [],
  },
];

export const relatedCapabilityEdges = capabilities.flatMap((capability) =>
  capability.relatedCapabilityIds.map((to) => ({ from: capability.id, to })),
);
