import type { EvidenceRecord } from "./types";

export const evidenceRecords: readonly EvidenceRecord[] = [
  {
    id: "bdb-electron",
    projectId: "bdb",
    capabilityId: "electron",
    claim: "Public-safe summary identifies an Electron desktop interface.",
    visibility: "owner_verified_private",
    verificationLevel: "owner_verified_private",
    sourceLabel: "BDB owner-verified public-safe summary",
  },
  {
    id: "bdb-mcp",
    projectId: "bdb",
    capabilityId: "mcp",
    claim: "Public-safe summary identifies Model Context Protocol integration work.",
    visibility: "owner_verified_private",
    verificationLevel: "owner_verified_private",
    sourceLabel: "BDB owner-verified public-safe summary",
  },
  {
    id: "bdb-ai-automation",
    projectId: "bdb",
    capabilityId: "ai-automation",
    claim: "Public-safe summary identifies AI-assisted workflow automation.",
    visibility: "owner_verified_private",
    verificationLevel: "owner_verified_private",
    sourceLabel: "BDB owner-verified public-safe summary",
  },
  {
    id: "distribution-desk-electron",
    projectId: "distribution-desk",
    capabilityId: "electron",
    claim: "Public-safe summary identifies an Electron desktop publishing workspace.",
    visibility: "owner_verified_private",
    verificationLevel: "owner_verified_private",
    sourceLabel: "Distribution Desk owner-verified public-safe summary",
  },
  {
    id: "distribution-desk-publishing-workflow",
    projectId: "distribution-desk",
    capabilityId: "publishing-workflow",
    claim: "Public-safe summary identifies desktop publishing workflow support.",
    visibility: "owner_verified_private",
    verificationLevel: "owner_verified_private",
    sourceLabel: "Distribution Desk owner-verified public-safe summary",
  },
  {
    id: "distribution-desk-integration-workflow",
    projectId: "distribution-desk",
    capabilityId: "integration-workflow",
    claim: "Public-safe summary identifies product integration workflow foundations.",
    visibility: "owner_verified_private",
    verificationLevel: "owner_verified_private",
    sourceLabel: "Distribution Desk owner-verified public-safe summary",
  },
  {
    id: "weekfield-ai-automation",
    projectId: "weekfield",
    capabilityId: "ai-automation",
    claim: "CreatorOps public case identifies AI-assisted creator operations.",
    visibility: "portfolio_case",
    verificationLevel: "portfolio_public",
    sourceLabel: "CreatorOps public case",
    sourceReference: "https://brenychstudio.com/work/creatorops",
  },
  {
    id: "weekfield-supabase",
    projectId: "weekfield",
    capabilityId: "supabase",
    claim: "CreatorOps public case identifies a Supabase-backed operations workflow.",
    visibility: "portfolio_case",
    verificationLevel: "portfolio_public",
    sourceLabel: "CreatorOps public case",
    sourceReference: "https://brenychstudio.com/work/creatorops",
  },
  {
    id: "weekfield-operator-workflow",
    projectId: "weekfield",
    capabilityId: "operator-workflow",
    claim: "CreatorOps public case identifies an operator-facing workflow.",
    visibility: "portfolio_case",
    verificationLevel: "portfolio_public",
    sourceLabel: "CreatorOps public case",
    sourceReference: "https://brenychstudio.com/work/creatorops",
  },
  {
    id: "sprintcrm-crm",
    projectId: "sprintcrm",
    capabilityId: "crm",
    claim: "Public case identifies a CRM workspace.",
    visibility: "portfolio_case",
    verificationLevel: "verified_remote",
    sourceLabel: "SprintCRM public case",
    sourceReference: "https://brenychstudio.com/work/sprintcrm",
  },
  {
    id: "sprintcrm-gmail-communication",
    projectId: "sprintcrm",
    capabilityId: "gmail-communication",
    claim: "Public case identifies Gmail-centered communication workflows.",
    visibility: "portfolio_case",
    verificationLevel: "verified_remote",
    sourceLabel: "SprintCRM public case",
    sourceReference: "https://brenychstudio.com/work/sprintcrm",
  },
  {
    id: "sprintcrm-operator-workflow",
    projectId: "sprintcrm",
    capabilityId: "operator-workflow",
    claim: "Public case identifies operator-led workflow support.",
    visibility: "portfolio_case",
    verificationLevel: "verified_remote",
    sourceLabel: "SprintCRM public case",
    sourceReference: "https://brenychstudio.com/work/sprintcrm",
  },
  {
    id: "sprintcrm-supabase",
    projectId: "sprintcrm",
    capabilityId: "supabase",
    claim: "Public case identifies a Supabase-backed CRM workflow.",
    visibility: "portfolio_case",
    verificationLevel: "verified_remote",
    sourceLabel: "SprintCRM public case",
    sourceReference: "https://brenychstudio.com/work/sprintcrm",
  },
  {
    id: "storyform-electron",
    projectId: "storyform",
    capabilityId: "electron",
    claim: "Local verification identifies Electron desktop editorial tooling.",
    visibility: "owner_verified_private",
    verificationLevel: "verified_local",
    sourceLabel: "StoryForm local verification",
  },
  {
    id: "storyform-media-workflow",
    projectId: "storyform",
    capabilityId: "media-workflow",
    claim: "Local verification identifies desktop editorial media workflow tooling.",
    visibility: "owner_verified_private",
    verificationLevel: "verified_local",
    sourceLabel: "StoryForm local verification",
  },
  {
    id: "native-site-control-architecture",
    projectId: "native-site-control",
    capabilityId: "site-control-architecture",
    claim: "Local verification identifies site-control architecture foundations.",
    visibility: "owner_verified_private",
    verificationLevel: "verified_local",
    sourceLabel: "Native Site Control local verification",
  },
  {
    id: "native-site-control-contracts",
    projectId: "native-site-control",
    capabilityId: "control-contracts",
    claim: "Local verification identifies control contract foundations.",
    visibility: "owner_verified_private",
    verificationLevel: "verified_local",
    sourceLabel: "Native Site Control local verification",
  },
  {
    id: "native-site-control-manifest-revision-validation",
    projectId: "native-site-control",
    capabilityId: "manifest-revision-validation",
    claim: "Local verification identifies manifest, revision, diff, validation, apply, and verification foundations.",
    visibility: "owner_verified_private",
    verificationLevel: "verified_local",
    sourceLabel: "Native Site Control local verification",
  },
  {
    id: "presence-webgl-3d-web",
    projectId: "presence-os-memory-atlas",
    capabilityId: "webgl-3d-web",
    claim: "Public case identifies an interactive three-dimensional web experience.",
    visibility: "portfolio_case",
    verificationLevel: "portfolio_public",
    sourceLabel: "Presence OS Memory Atlas public case",
    sourceReference: "https://brenychstudio.com/immersive/presence-os-memory-atlas",
  },
  {
    id: "presence-webxr",
    projectId: "presence-os-memory-atlas",
    capabilityId: "webxr",
    claim: "Public case identifies WebXR interface exploration.",
    visibility: "portfolio_case",
    verificationLevel: "portfolio_public",
    sourceLabel: "Presence OS Memory Atlas public case",
    sourceReference: "https://brenychstudio.com/immersive/presence-os-memory-atlas",
  },
  {
    id: "presence-spatial-archive",
    projectId: "presence-os-memory-atlas",
    capabilityId: "spatial-archive",
    claim: "Public case identifies a spatial archive interface.",
    visibility: "portfolio_case",
    verificationLevel: "portfolio_public",
    sourceLabel: "Presence OS Memory Atlas public case",
    sourceReference: "https://brenychstudio.com/immersive/presence-os-memory-atlas",
  },
  {
    id: "presence-interactive-interface",
    projectId: "presence-os-memory-atlas",
    capabilityId: "interactive-interface",
    claim: "Public case identifies an interactive interface.",
    visibility: "portfolio_case",
    verificationLevel: "portfolio_public",
    sourceLabel: "Presence OS Memory Atlas public case",
    sourceReference: "https://brenychstudio.com/immersive/presence-os-memory-atlas",
  },
];
