import type { Project } from "./types";

export const projects: readonly Project[] = [
  {
    id: "bdb",
    displayName: "BDB",
    publicName: "BDB",
    productType: "Desktop agent interface",
    maturity: "owner_verified_implementation",
    maturityLabel: "OWNER-VERIFIED IMPLEMENTATION",
    visibility: "public_summary_only",
    verificationLevels: ["owner_verified_private"],
    summary:
      "A local-first, provider-agnostic development context and control plane for safe multi-project software development.",
    verifiedHighlights: [
      "Local-first development control plane",
      "Bounded repository context",
      "Human-reviewed source authority",
      "Durable multi-file recovery",
      "MCP interoperability",
    ],
    capabilityIds: ["electron", "mcp", "ai-automation"],
    limitations: [
      "Only the public-safe summary is represented.",
      "No repository, prompts, credentials, or internal operations are included.",
    ],
    links: [],
    prohibitedClaims: ["Production deployment status", "Private implementation details"],
  },
  {
    id: "distribution-desk",
    displayName: "Distribution Desk",
    publicName: "Distribution Desk",
    productType: "Desktop publishing workspace",
    maturity: "owner_verified_implementation",
    maturityLabel: "OWNER-VERIFIED IMPLEMENTATION",
    visibility: "public_summary_only",
    verificationLevels: ["owner_verified_private"],
    summary:
      "A local Electron desktop application for content adaptation, campaign workflow, scheduling and direct publishing through official platform APIs.",
    verifiedHighlights: [
      "Electron publishing workspace",
      "Official platform API architecture",
      "Durable publication queue",
      "Provider adapters",
      "Credential isolation",
    ],
    capabilityIds: ["electron", "publishing-workflow", "integration-workflow"],
    limitations: [
      "Only public-safe desktop publishing and integration claims are represented.",
      "No customer data or private source material is included.",
    ],
    links: [],
    prohibitedClaims: ["Customer outcomes", "Private implementation details"],
  },
  {
    id: "weekfield",
    displayName: "Weekfield",
    publicName: "Weekfield",
    publicEvidenceName: "CreatorOps",
    productType: "Creator operations workspace",
    maturity: "beta_ready_prototype",
    maturityLabel: "PRODUCTION-CONNECTED PAID SAAS RELEASE CANDIDATE · CONTROLLED BETA",
    visibility: "public",
    verificationLevels: ["portfolio_public"],
    summary:
      "A production-connected paid SaaS release candidate in controlled beta, with deterministic Smart Mix, Planet Field and human-reviewed proposal/apply boundaries.",
    verifiedHighlights: [
      "Production-connected controlled beta",
      "Deterministic Smart Mix",
      "Planet Field",
      "Human-reviewed proposal / apply boundary",
      "Supabase-backed workflow",
    ],
    capabilityIds: ["ai-automation", "supabase", "operator-workflow"],
    limitations: [
      "The public case does not establish private implementation details.",
      "CreatorOps is the public evidence name for this canonical Weekfield record.",
    ],
    links: [{ label: "CreatorOps public case", href: "https://brenychstudio.com/work/creatorops", kind: "case_study" }],
    prohibitedClaims: ["Separate CreatorOps project count", "Private implementation details"],
  },
  {
    id: "sprintcrm",
    displayName: "SprintCRM",
    publicName: "SprintCRM",
    productType: "CRM workspace",
    maturity: "public_case",
    maturityLabel: "VERIFIED PUBLIC CASE",
    visibility: "public",
    verificationLevels: ["verified_remote"],
    summary: "A CRM interface for operator-led communication workflows.",
    verifiedHighlights: [
      "Public CRM workspace",
      "Gmail-centered communication workflow",
      "Operator-led workflow",
      "Supabase-backed product state",
    ],
    capabilityIds: ["crm", "gmail-communication", "operator-workflow", "supabase"],
    limitations: [
      "Public evidence does not include contact data or customer records.",
      "No delivery or adoption metrics are claimed.",
    ],
    links: [
      { label: "Public case", href: "https://brenychstudio.com/work/sprintcrm", kind: "case_study" },
      { label: "Public repository", href: "https://github.com/brenychstudio/SprintCRM", kind: "repository" },
    ],
    prohibitedClaims: ["Customer data access", "Production adoption metrics"],
  },
  {
    id: "storyform",
    displayName: "StoryForm",
    publicName: "StoryForm",
    productType: "Desktop editorial media tooling",
    maturity: "owner_verified_implementation",
    maturityLabel: "OWNER-VERIFIED IMPLEMENTATION",
    visibility: "public_summary_only",
    verificationLevels: ["verified_local"],
    summary:
      "A local Electron storyboard-first narrative creation system with local media, composition, analysis, rendering, persistence, Motion Lab and an AI adapter boundary.",
    verifiedHighlights: [
      "Electron storyboard-first authoring",
      "Local media workflow",
      "Composition / Motion Lab",
      "Render pipeline",
    ],
    capabilityIds: ["electron", "media-workflow"],
    limitations: [
      "Only the public-safe desktop tooling summary is represented.",
      "No private source or collaborator material is included.",
    ],
    links: [],
    prohibitedClaims: ["Private source availability", "Unverified performance claims"],
  },
  {
    id: "native-site-control",
    displayName: "Native Site Control",
    publicName: "Native Site Control",
    productType: "Site-control foundation",
    maturity: "owner_verified_implementation",
    maturityLabel: "OWNER-VERIFIED IMPLEMENTATION",
    visibility: "public_summary_only",
    verificationLevels: ["verified_local"],
    summary: "A public-safe summary of site-control architecture foundations.",
    verifiedHighlights: [
      "Framework-independent control foundation",
      "Explicit control contracts",
      "Manifest / revision validation",
      "Human-controlled apply foundations",
    ],
    capabilityIds: [
      "site-control-architecture",
      "control-contracts",
      "manifest-revision-validation",
    ],
    limitations: [
      "The scope is limited to control architecture, contracts, and manifest/revision validation foundations.",
      "No repository or private implementation detail is represented.",
    ],
    links: [],
    prohibitedClaims: ["Native iOS implementation", "Private repository access"],
  },
  {
    id: "presence-os-memory-atlas",
    displayName: "Presence OS Memory Atlas",
    publicName: "Presence OS Memory Atlas",
    productType: "Spatial web archive",
    maturity: "functional_mvp_prototype",
    maturityLabel: "FUNCTIONAL PUBLIC MVP PROTOTYPE",
    visibility: "public",
    verificationLevels: ["portfolio_public"],
    summary: "An interactive spatial archive presented as a public web experience.",
    verifiedHighlights: [
      "Public spatial web archive",
      "WebGL / 3D web",
      "WebXR exploration",
      "Interactive archive interface",
    ],
    capabilityIds: ["webgl-3d-web", "webxr", "spatial-archive", "interactive-interface"],
    limitations: [
      "Public evidence supports web-based spatial work only.",
      "It does not establish native platform or hardware capabilities.",
    ],
    links: [
      {
        label: "Public immersive experience",
        href: "https://brenychstudio.com/immersive/presence-os-memory-atlas",
        kind: "site",
      },
    ],
    prohibitedClaims: ["Native XR application delivery", "Private implementation details"],
  },
];
